import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Generate a PDF for an assessment
 * @param {Object} assessment - The assessment data
 */
export const generateAssessmentPDF = (assessment) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  
  // --- Header ---
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(assessment.title || "Assessment", pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Subject: ${assessment.subject || "General"}`, 14, 35);
  doc.text(`Duration: ${assessment.duration || 60} mins`, pageWidth - 14, 35, { align: 'right' });
  
  doc.text(`Total Marks: ${assessment.totalMarks || 0}`, 14, 42);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 14, 42, { align: 'right' });
  
  doc.line(14, 48, pageWidth - 14, 48); // Horizontal line
  
  // --- Instructions ---
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text("Instructions: Answer all questions. Write clearly and legibly.", 14, 55);
  
  let yPos = 65;
  
  // --- Questions ---
  const questions = assessment.questions || [];
  
  questions.forEach((q, index) => {
    // Check if we need a new page
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    
    // Question Number and Text
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    const questionTitle = `Q${index + 1}. (${q.marks} marks)`;
    doc.text(questionTitle, 14, yPos);
    
    doc.setFont('helvetica', 'normal');
    const splitQuestion = doc.splitTextToSize(q.question, pageWidth - 28);
    doc.text(splitQuestion, 14, yPos + 6);
    
    yPos += 6 + (splitQuestion.length * 5);
    
    // Options for MCQs
    if (q.type === 'MCQ' && q.options && q.options.length > 0) {
      q.options.forEach((opt, optIndex) => {
        if (yPos > 280) {
          doc.addPage();
          yPos = 20;
        }
        const optionLabel = String.fromCharCode(65 + optIndex); // A, B, C, D
        doc.text(`${optionLabel}. ${opt}`, 20, yPos);
        yPos += 6;
      });
      yPos += 4; // Extra space after options
    } else if (q.type === 'Short Answer') {
      // Add lines for answer
      yPos += 5;
      if (yPos > 270) { doc.addPage(); yPos = 20; }
      doc.setDrawColor(200);
      doc.line(14, yPos, pageWidth - 14, yPos);
      doc.line(14, yPos + 8, pageWidth - 14, yPos + 8);
      doc.line(14, yPos + 16, pageWidth - 14, yPos + 16);
      yPos += 24;
    } else if (q.type === 'Long Answer') {
      // Add more lines for answer
      yPos += 5;
      if (yPos > 250) { doc.addPage(); yPos = 20; }
      doc.setDrawColor(200);
      for (let i = 0; i < 6; i++) {
        doc.line(14, yPos + (i * 8), pageWidth - 14, yPos + (i * 8));
      }
      yPos += 56;
    } else {
      yPos += 10; // Default spacing
    }
    
    yPos += 4; // Spacing between questions
  });
  
  // --- Footer ---
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(`Page ${i} of ${pageCount} - Generated by PaperGenie`, pageWidth / 2, 290, { align: 'center' });
  }
  
  // Save the PDF
  doc.save(`${assessment.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
};
